name: Run process.py every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:  # allows manual runs too

jobs:
  run-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run process.py
        run: python process.py
